### ISSUE TITLE
Safari on mobile Sliding down the page will automatic  Snap back to the top

### ISSUE THREAD

**Issue by Evanl-lai** [greensock/GSAP#529]
"gsap": "^3.11.4",

Hello~
There was a serious problem in my project，

The main performance is to slide down the page,Safari on mobile Sliding down the page will automatic  back to the top。

In our test，It is mainly displayed in ios15.2 and above，Android is ok

We can't find the cause. Please help me，thanks~

 i try use ScrollTrigger.normalizeScroll(true);  But this can Cause Kartun

**Comment by jackdoyle** [comment]
Sorry to hear about the trouble, @Evanl-lai Do you have a minimal demo (like a CodePen) we could look at? 

Please try the beta version of the upcoming release which you can get at https://assets.codepen.io/16327/ScrollTrigger.min.js (you may need to clear your cache). Does that resolve things?

**Comment by Evanl-lai** [comment]
Hi Jack

hank you for helping and answering our issues on GitHub

You can take a look at this video，What I just did was just slide down and not sliding up and you can see it automatically coming back to the top

Am I the only one with this problem, has anyone else mentioned this to you? If I have to, all I can think of is banning mobile devices,

https://user-images.githubusercontent.com/58460652/223647234-23ee3e7b-cd82-47c5-856b-a5713829d413.mp4

**Comment by jackdoyle** [comment]
No no, you definitely don't need to ban mobile devices. ScrollTrigger works on all devices. 

I do remember a few edge cases that people said they ran into with ScrollTrigger returning to the top, but those were resolved already. Are you positive you're using the latest version? And did you try the latest beta file I linked to? Are you saying that does NOT resolve the issue?

**Comment by Evanl-lai** [comment]
Yes, I replaced ScrollTrigger.min.js in the npm package according to the test document you provided,。 but the problem still exists,which was confusing。


```javascript
import { gsap } from "gsap";
import { ScrollTrigger } from "gsap/dist/ScrollTrigger.min.js";
// import { ScrollToPlugin } from "gsap/ScrollToPlugin";
import { Draggable } from "gsap/Draggable";

gsap.registerPlugin(ScrollTrigger, Draggable);
// ScrollTrigger.normalizeScroll(true);
ScrollTrigger.defaults({
    // toggleActions: "restart pause restart pause",
});

export { gsap, ScrollTrigger, Draggable };
```

![image](https://user-images.githubusercontent.com/58460652/223902948-c142090c-e265-4643-a2ce-bd1a94daba17.png)

**Comment by jackdoyle** [comment]
Hm, that seems a little odd that you're importing an ES5 minified file as a module like that. Maybe it's fine in your environment.

Can you please provide a minimal demo that clearly shows the issue? A CodePen is ideal. A Stackblitz or CodeSandbox is okay too. Just some colored <div> elements is fine - please don't include your whole project. The simpler the better. 

It's just very difficult to troubleshoot blind. I suspect there's something else going on in your project but I can't tell for sure. Tons of people use ScrollTrigger on mobile devices and do NOT get the behavior you're describing. If ScrollTrigger was doing that on all mobile devices, we'd surely be hearing tons of complaints but we're not. So something is different with your particular project. 

I'm also curious what you see if you add a console.log(ScrollTrigger.version) in your code. Are you definitely seeing 3.11.5 in the console? I'm trying to make sure you aren't loading an older one on top of 3.11.5 and it's overwriting it or something. 

Once I see a minimal demo I'm sure it'll become much more clear. 

Oh, and you don't have scroll-behavior: smooth in your CSS for the html/body do you? That's a very bad idea because it's sorta like applying CSS transitions to things that you're animating with JS. It totally interferes.

**Comment by Evanl-lai** [comment]
Wow Thank you very much for your thoughts at the end！
  
           I didn't read the document carefully, scroll-behavior: smooth does exist in my html/body CSS, I deleted and finally solved the problem, This property is really unfriendly to gsap hahaha，Have a nice day !

**Comment by Evanl-lai** [comment]
Wow Thank you very much for your thoughts at the end！ 
 
I didn't read the document carefully, scroll-behavior: smooth does exist in my html/body CSS, I deleted and finally solved the problem, This property is really unfriendly to gsap hahaha，Have a nice day !

**Comment by jackdoyle** [comment]
Ah, okay, that makes sense. Glad it's figured out now. Good luck with your project.
